version: "3"
services:
  app:
    container_name: "app"
    image: app
    environment:
      - MONGODB_URL=mongodb://root:super-secret-password@mongo_db:27017
      - SECRET=please_please_update_me_please
      - ALGORITHM=HS256
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db
    wolumes:
      - static: /backend/static

  mongo_db:
    container_name: "mongo_db"
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=super-secret-password
    networks:
      - custom

volumes:
  custom:
    driver: bridge

networks:
  custom:
    driver: bridge
