version: "3"
services:
  app:
    container_name: "app"
    image: app
    environment:
      - MONGODB_URL=mongodb://mongo_db
      - SECRET=please_please_update_me_please
      - ALGORITHM=HS256
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db
      - elasticsearch

  mongo_db:
    container_name: "mongo_db"
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - custom

  elasticsearch:
    container_name: "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment: 
      - cluster.name=elasticsearch
      - network.bind_host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - discovery.type=single-node
      - "CLI_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - custom
    ports:
      - 9200:9200

  kibana:
    container_name: "kibana"
    image: docker.elastic.co/kibana/kibana:8.10.2
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    networks:
      - custom
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  custom:
    driver: bridge